weather_api_key: ${WEATHER_API_KEY}

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: journaldb
      auto-index-creation: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${JAVA_EMAIL}
    password: ${JAVA_EMAIL_PASSWORD}

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
      port: 8080
      servlet:
        context-path:

redis:
  host: localhost
  port: 6379

#  kafka:
#    bootstrap-servers: pkc-l7pr2.ap-south-1.aws.confluent.cloud:9092
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#    consumer:
#      group-id: weekly-sentiment-group
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#      spring:
#        json:
#            trusted:
#              packages: net.engineeringdigest.journalApp.model
#    properties:
#        security:
#          protocol: SASL_SSL
#        sasl:
#          mechanism: PLAIN
#          jaas:
#          config: org.apache.kafka.common.security.plain.PlainLoginModule required username='VCMV4GVRDSZFRCLU' password='cflt4alR/rrWd8VJr5AuC+VU38AN4uTMjmODTqY8phHFm4J/E8zU2McrgVXQmnGg';
#
#    session:
#        timeout:
#          ms: '45000'
#    client:
#      id: ccloud-springboot-client-b84bca7f-4b21-4020-950b-1bf7ecb26806